server:
  port: 9002

spring:
  application:
    name: game-service
  data:
    mongodb:
      uri: mongodb+srv://${GAMEINN_DB_CREDENTIALS}@gameinn.cjnkrd4.mongodb.net/GAMES?retryWrites=true&w=majority


feign:
  userservice:
    url: ${USER_SERVICE:http://localhost:9001}
  reviewservice:
    url: ${REVIEW_SERVICE:http://localhost:9003}
