server:
  port: 9002

spring:
  application:
    name: GAME-SERVICE
  zipkin:
    base-url: http://localhost:9411/
  data:
    mongodb:
      uri: mongodb+srv://faruk:faruk1234@gameinn.cjnkrd4.mongodb.net/deneme?retryWrites=true&w=majority