server:
  port: 9002

spring:
  application:
    name: game-service
  data:
    mongodb:
      uri: ${GAMEINN_DB_URI}


feign:
  userservice:
    url: ${USER_SERVICE:http://localhost:9001}
  reviewservice:
    url: ${REVIEW_SERVICE:http://localhost:9003}
