server:
  port: 9000

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE:http://localhost:9001}
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
        - id: game-service
          uri: ${GAME_SERVICE:http://localhost:9002}
          predicates:
            - Path=/game/**
          filters:
            - AuthenticationFilter
        - id: review-service
          uri: ${REVIEW_SERVICE:http://localhost:9003}
          predicates:
            - Path=/review/**
          filters:
            - AuthenticationFilter
        - id: authentication-service
          uri: ${AUTHENTICATION_SERVICE:http://localhost:9090}
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
jwt:
  spring:
    web-application-type: reactive

