server:
  port: 9080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
        - id: game-service
          uri: lb://game-service
          predicates:
            - Path=/game/**
          filters:
            - AuthenticationFilter
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review/**
          filters:
            - AuthenticationFilter
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

jwt:
  spring:
    web-application-type: reactive


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true