server:
  port: 9001

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${GAMEINN_DB_URI}
      auto-index-creation: true


feign:
  gameservice:
    url: ${GAME_SERVICE:http://localhost:9002}
  reviewservice:
    url: ${REVIEW_SERVICE:http://localhost:9003}

