server:
  port: 9001

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://faruk:faruk1234@gameinn.cjnkrd4.mongodb.net/USERS?retryWrites=true&w=majority
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true