server:
  port: 9001

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://${GAMEINN_DB_CREDENTIALS}@gameinn.cjnkrd4.mongodb.net/USERS?retryWrites=true&w=majority
      auto-index-creation: true


feign:
  gameservice:
    url: ${GAME_SERVICE:http://localhost:9002}
  reviewservice:
    url: ${REVIEW_SERVICE:http://localhost:9003}

