server:
  port: 9003

spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb+srv://faruk:faruk1234@gameinn.cjnkrd4.mongodb.net/REVIEWS?retryWrites=true&w=majority

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true