server:
  port: 9003

spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb+srv://${GAMEINN_DB_CREDENTIALS}@gameinn.cjnkrd4.mongodb.net/REVIEWS?retryWrites=true&w=majority
      auto-index-creation: true


feign:
  gameservice:
    url: ${GAME_SERVICE:http://localhost:9002}
  userservice:
    url: ${USER_SERVICE:http://localhost:9001}


