server:
  port: 9003

spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: ${GAMEINN_DB_URI}
      auto-index-creation: true


feign:
  gameservice:
    url: ${GAME_SERVICE:http://localhost:9002}
  userservice:
    url: ${USER_SERVICE:http://localhost:9001}


